---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/24 11:15
---

--锁的key
local key = KEYS[1]

--当前线程标识
local threadId = ARGV[1]

--get key
local id = redis.call('get',key)

--比较线程标识与锁中的标识是否一致
if(id==threadId) then
    --释放锁
   return redis.call('del',key)
end

return 0