---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/1/14 19:53
---
--- 1.参数列表
---1.1 优惠券id
local vocherId = ARGV[1]

--- 1.2 用户id
local userId = ARGV[2]

-- 2. 数据key
-- 2.1 库存
local stockKey = 'seckill:stock:' .. vocherId  --.. 是 Lua中的字符串连接运算符
-- 2.2 订单key
local orderKey = 'seckill:order:' .. vocherId

-- 3 脚本业务
-- 3.1判断库存是否充足
if(tonumber(redis.call('get',stockKey))<=0) then
    -- 3.2库存不足返回1
    return 1
end

-- 3.2判断用户是否下单 SISMEMBER orderKey userId
if(redis.call('sismember',orderKey,userId)==1) then
    -- 3.3 存在说明重复下单
    return 2
end

-- 3.4扣库存
redis.call('incrby',stockKey,-1)
-- 下单（保存用户）
redis.call('sadd',orderKey,userId)
return 0